services:
  building-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: building-management-app
    volumes:
      - .:/app
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"